server {
    listen 80;
    server_name #openhim.s2.openimis.org;


    # Serve OpenHIM Console (UI) at / default openhim console port
    location / {
        proxy_pass http://localhost:9000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location ~ ^/(heartbeat|authenticate|users|me|sessions|clients|roles|permissions|transactions|orchestrations|logs|channels|stats|status|mediators|groups|audits|visualizers|cert|validity|metrics|about|tasks)(/.*)?$ {
        proxy_pass https://localhost:8080$request_uri;
        proxy_ssl_verify off;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
    # Proxy /heartbeat (and other OpenHIM Core APIs) to 8080
    # Optional: proxy the rest of the core API
    location /api/ {
        proxy_pass https://localhost:8080/;
        proxy_set_header Host $host;
        proxy_ssl_verify off;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
