version: '3.8'

networks:
  traefik_proxy:
    name: ${PROJECT_NAME:-sandbox}-traefik_proxy

services:
  traefik:
    image: "traefik:latest"
    container_name: "traefik"
    networks:
      - traefik_proxy
    command:
      - "--log.level=DEBUG"  # Change to INFO, WARN, ERROR if needed
      - "--accesslog=true"   # Enable access logs
      #- "--accesslog.filepath=/var/log/traefik/access.log"
      #- "--log.filepath=/var/log/traefik/traefik.log"
      - "--api.insecure=true"
      - "--providers.file.watch=true"
      - "--providers.docker=true"
      - "--api=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.file.filename=/dynamic.yml"
      - "--entrypoints.http.address=:80"
      - "--entrypoints.https.address=:443"
      # Enable Let's Encrypt with HTTP challenge
      - "--certificatesResolvers.letsencrypt.acme.tlsChallenge=true"
      - "--certificatesResolvers.letsencrypt.acme.email=contact@s2.openimis.org"
      - "--certificatesResolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
      #- "--certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt$
      # Redirect all HTTP to HTTPS
      - "--entrypoints.http.http.redirections.entryPoint.to=https"
      - "--entrypoints.http.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.http.http.redirections.entryPoint.permanent=true"
    ports:
      - "80:80"
      - "443:443"
      - "127.0.0.1:8080:8080"
    labels:
      # Dashboard
      - "traefik.http.routers.traefik.rule=Host(`sb-setup-traefik.bastion.y-note.cm`)"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.entrypoints=https"
      # **add** our redirect middleware here
      - "traefik.http.routers.traefik-dashboard.middlewares=dashboard-redirect"

      # middleware that only kicks in when the request path is exactly "/"
      - "traefik.http.middlewares.dashboard-redirect.redirectregex.regex=^/$"
      - "traefik.http.middlewares.dashboard-redirect.redirectregex.replacement=/dashboard/"
      - "traefik.http.middlewares.dashboard-redirect.redirectregex.permanent=true"

      # Global redirect to HTTPS
      - "traefik.http.routers.traefik.tls.certresolver=letsencrypt"
      - "traefik.http.routers.http-catchall.rule=hostregexp(`{host:.+}`)"
      - "traefik.http.routers.http-catchall.entrypoints=http"
      - "traefik.http.routers.http-catchall.middlewares=redirect-to-https"

      # Middleware redirect
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./logs:/var/log/traefik"
      - "./dynamic.yml:/dynamic.yml:ro"
      - "./data/letsencrypt:/letsencrypt"
    restart: always