http:
  routers:
    openspp:
      rule: Host(`openspp.s2.openimis.org`)
      entryPoints: [https]
      service: openspp
      tls:
    certResolver: letsencrypt

    bahmni:
      rule: Host(`bahmni.s2.openimis.org`)
      entryPoints: [https]
      service: bahmni
      tls:
        certResolver: letsencrypt

    odoo:
      rule: Host(`odoo.s2.openimis.org`)
      entryPoints: [https]
      service: odoo
      tls:
        certResolver: letsencrypt

    openimis:
      rule: Host(`openimis.s2.openimis.org`)
      entryPoints: [https]
      service: openimis
      tls:
        certResolver: letsencrypt

    openimisdev:
      rule: Host(`openimisdev.s2.openimis.org`)
      entryPoints: [https]
      service: openimisdev
      tls:
        certResolver: letsencrypt

    openhimconsole:
      rule: Host(`openhim.s2.openimis.org`)
      entryPoints: [https]
      service: openhimconsole
      tls:
        certResolver: letsencrypt

    cht:
      rule: Host(`cht.s2.openimis.org`)
      entryPoints: [https]
      service: cht
      tls:
        certResolver: letsencrypt
    glitchtip:
      rule: Host(`glitchtip.s2.openimis.org`)
      entryPoints: [https]
      service: glitchtip
      tls:
        certResolver: letsencrypt
        
    mailpit:
      rule: Host(`mailpit.s2.openimis.org`)
      entryPoints: [https]
      service: mailpit
      tls:
        certResolver: letsencrypt

  services:
    openspp:
      loadBalancer:
        servers:
          - url: http://192.168.11.192:17069

    bahmni:
      loadBalancer:
        servers:
          - url: https://192.168.11.192:443
        passHostHeader: true
        serversTransport: bahmni-transport

    odoo:
      loadBalancer:
        servers:
          - url: http://192.168.11.192:8069

    openimis:
      loadBalancer:
        servers:
          - url: http://192.168.11.230:80

    openimisdev:
      loadBalancer:
        servers:
          - url: http://192.168.11.230:81

    openhimconsole:
      loadBalancer:
        servers:
          - url: http://192.168.11.31:80

    cht:
      loadBalancer:
        servers:
          - url: https://192.168.11.122:443
        passHostHeader: true
        serversTransport: cht-transport

    glitchtip:
      loadBalancer:
        servers:
          - url: http://192.168.11.221:8000

    mailpit:
      loadBalancer:
        servers:
          - url: http://192.168.11.221:8025

  serversTransports:
    bahmni-transport:
      insecureSkipVerify: true
    cht-transport:
      insecureSkipVerify: true