version: '3'
networks:
  openhim:
    external: true
    name: openhim-common_default

services:
  db:
    image: postgres:14.2
    # ports:
    #   - 5432:5432
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db-data:/data/postgres
    networks:
      - openhim

  web:
    build:
      context: .
      args:
        REQUIREMENTS_FILE: dev.txt
    restart: always
    ports:
      - 8001:8000
    env_file: .env
    command: 'sh -c "cp pre-commit.example .git/hooks/pre-commit && chmod +x .git/hooks/pre-commit && ./manage.py migrate && ./manage.py runserver 0.0.0.0:8000"'
    volumes:
      - ./:/app
    depends_on:
      - db
    networks:
      - openhim
  #  disabled for now
  # queue:
  #   build:
  #     context: .
  #     args:
  #       REQUIREMENTS_FILE: dev.txt
  #   restart: unless-stopped
  #   env_file: .env
  #   command: sh /entrypoint-queue.sh
  #   volumes:
  #     - ./:/app
  #   networks:
  #     - openhim

  # beat:
  #   build:
  #     context: .
  #     args:
  #       REQUIREMENTS_FILE: dev.txt
  #   restart: unless-stopped
  #   env_file: .env
  #   command: sh /entrypoint-beat.sh
  #   volumes:
  #     - ./:/app
  #   networks:
  #     - openhim

  # redis:
  #   image: redis:alpine
  #   restart: unless-stopped
  #   ports:
  #     - 6379:6379
  #   networks:
  #     - openhim

  # mailhog:
  #   image: mailhog/mailhog:latest
  #   restart: always
  #   ports:
  #     - 1025:1025
  #     - 8025:8025
  #   networks:
  #     - openhim

volumes:
  db-data:
