# docker-compose.yml

version: '3.8'

services:
  mediator:
    build: .
    ports:
      - "5001:5001"
    volumes:
      - .:/app
      - db_data:/app/notifications.db
    env_file:
      - .env

volumes:
  db_data:
